apiVersion: v1
kind: Service
metadata:
  name: testserver-service
  labels:
    name: testserver-service
spec:
  type: ClusterIP
  ports:
    - port: 8032
      targetPort: http
      protocol: TCP
      name: http
  selector:
    name: testserver
